FROM fedora:28

LABEL description="Epitech Docker based on Fedora 28 for continuous integration and continuous deployment."
LABEL maintener="Cyberry Team"

COPY /scripts /tmp/scripts

RUN ["bash", "/tmp/scripts/install.sh", "c", "rm"]