name: Pull Request

on:
  pull_request:
    branches: [ 'ubuntu*' ]

env:
  DOCKER_IMAGE_USER: cyberryteam
  DOCKER_IMAGE_NAME: epitech-docker

jobs:

  docker:
    strategy:
      matrix:
        packages:
          - "all"
          - "core"
          - "c"
          - "cpp"
          - "python"

    name: Docker for ${{ matrix.packages }}
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker build . \
            -t $DOCKER_IMAGE_USER/$DOCKER_IMAGE_NAME:ubuntu \
            --build-arg IMAGE_PACKAGES=${{ matrix.packages }}

      - name: Test
        run: |
          chmod +x test/test.sh
          docker run --rm -v "$PWD/test:/tmp" $DOCKER_IMAGE_USER/$DOCKER_IMAGE_NAME:ubuntu ./test.sh ${{ matrix.packages }}

  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*.github/.*
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_MD: true
